language: cpp
compiler:
    - clang
notifications:
    email: true
before_install:
    - sudo add-apt-repository ppa:staticfloat/julia-deps -y
    - sudo add-apt-repository ppa:staticfloat/julianightlies -y
    - sudo apt-get update -qq -y
    - sudo apt-get install libpcre3-dev julia -y
    - git config --global user.name "Zach Allaun"
    - git config --global user.email "zach.allaun@gmail.com"
    - git submodule update --init --recursive
script:
    - julia -e "Pkg.init()"
    - mkdir -p ~/.julia/HttpServer
    - cp -R ./* ~/.julia/HttpServer/
    - julia -e 'Pkg.add("BinDeps")'
    - julia -e 'Pkg.add("FactCheck")'
    - julia -e 'Pkg.add("HttpCommon")'
    - julia -e 'Pkg.add("Calendar")'
    - julia -e 'Pkg.fixup("HttpServer")'
    - julia ~/.julia/HttpServer/test/test.jl
