language: cpp
compiler:
    - clang
    - gcc
notifications:
    email:
        - zach.allaun@gmail.com
        - daniel@danielespeset.com
before_install:
    - sudo add-apt-repository ppa:staticfloat/julia-deps -y
    - sudo add-apt-repository ppa:staticfloat/julianightlies -y
    - sudo apt-get update -qq -y
    - sudo apt-get install libpcre3-dev julia -y
    - git config --global user.name "Zach Allaun"
    - git config --global user.email "zach.allaun@gmail.com"
    - git submodule update --init --recursive
script:
    - julia -e "Pkg.init()"
    - julia -e 'run(`ln -s $(pwd()) $(Pkg.dir("HttpParser"))`); Pkg.pin("HttpParser"); Pkg.resolve(); Pkg.build("HttpParser")'
    - julia --code-coverage test/test.jl
after_success:
    - julia -e 'cd(Pkg.dir("HttpParser")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
